url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Visidra" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss

postcss:
  cache: false

# sass:
#   sass_dir: _sass
#   style: compressed

# sass:
#   load_paths:
#     - _sass
#     - node_modules

#include: ["node_modules/tailwindcss"]

exclude:
  - .git
  - .github
  - .gitignore
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
