url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Visidra" # the name of your site, e.g. ACME Corp.

livereload: true
# Google Analytics
google-analytics: G-ZGVETCG6PX

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - .git
  - .github
  - .gitignore
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
